admin_email: aknbdev@gmail.com

node:
  version: 18

app:
  name: Clinix Frontend
  host: clinix-frontend
  port: 3004
  domain: app.clinix.uz
  service_name: clinix-frontend.service
  home: /mnt/clinix-frontend
