admin_email: aknbdev@gmail.com

node:
  version: 18

app:
  name: Clinova Frontend
  host: clinova-frontend
  port: 3004
  domain: app.clinova.uz
  service_name: clinova-frontend.service
  home: /mnt/clinova-frontend
