admin_email: aknbdev@gmail.com

node:
  version: 18

app:
  name: Clinova Frontend
  host: clinova-frontend-dev
  port: 3006
  domain: app-dev.clinova.uz
  service_name: clinova-frontend-dev.service
  home: /mnt/clinova-frontend-dev
