---
- name: Infrastructure for application
  hosts: infra_hosts
  become: true
  roles:
    - nginx
    - letsencrypt
    - nodejs

- name: Deploying application to server
  hosts: app_hosts
  become: true
  roles:
    - app
