name: Check on pull request

on:
  pull_request:
    branches:
      - prod
    paths:
      - '.github/ansible/**'

env:
  setup_python: 'true'
  ANSIBLE_CONFIG: .github/ansible/ansible.cfg

jobs:
  ansible-lint:
    name: Ansible Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        if: env.setup_python == 'true'
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: .github/ansible/ansible-lint-requirements.txt
          python-version: "3.11"

      - name: Install ansible and ansible-lint from pip
        shell: bash
        run: |
          pip install ansible ansible-lint
          ansible-lint --version

      - name: Run ansible-lint
        shell: bash
        run: ansible-lint -v -p .github/ansible/**/*
