name: 'Continuous Integration and Deployment.'

on:
  push:
    branches:
        - main
    paths-ignore:
        - '.github/ansible/**'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install required nodejs dependencies
        run: npm ci --legacy-peer-deps
      - name: Build application code
        run: npm run build
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: .github/ansible/ansible-lint-requirements.txt
          python-version: "3.11"
      - name: Install ansible from pip
        shell: bash
        run: |
          pip install ansible
          ansible --version
      
      - name: Prepare ssh key from secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_RSA }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible playbook
        run: "ansible-playbook .github/ansible/site.yml -i .github/ansible/env/${{ github.ref_name }}/hosts -t deploy"
        env:
          ANSIBLE_CONFIG: .github/ansible/ansible.cfg
      
      - name: Clear ssh key
        run: |
          rm -rf ~/.ssh/id_rsa
